config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "welcome#index"
  

  get "/signup", to: "users#new", as: 'new_user_path'
  get "/login", to: "sessions#new", as: 'login_path'
  post "/login", to: "sessions#create"
  delete '/logout', to: "sessions#destroy", as: 'logout_path'
  get '/logout', to: "sessions#destroy"

  get '/auth/google_oauth2/callback', to: "sessions#google_login"

  resources :users 
  resources :assignments, only: [:index, :new, :create] 

  resources :user_assignments


  resources :users, only: [:show] do #nested resource for assignments
   resources :assignments, shallow: true
    resources :user_assignments, only: [:show, :index] #shows entire list of assignments and indiv assignments
  end 

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
    has_many :user_assignments
    has_many :users, through: :user_assignments#, source: :user_id
    has_one_attached :file
   
    
    
end 


app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password

    enum role: {student: 1, teacher: 2, admin: 3}
    has_many :user_assignments
    has_many :assignments, through: :user_assignments

    validates_presence_of :username

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    
    validates :password, confirmation: { case_sensitive: true }


    def student
      self.role == "student"
    end 

    def teacher
      self.role == "teacher"
    end 

    def admin
      @current_user.role == "admin"
    end 

    def full_name
      self.first_name + " " + self.last_name
    end 

    def self.all_students
      User.where(role: 'student')
    end 

  end

app/models/user_assignment.rb
class UserAssignment < ActiveRecord::Base 
    belongs_to :user
    belongs_to :assignment
    
    
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user
      


    def log_in(user)
        session[:user_id] = user.id
    end 

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end 

    def student_list
        User.where(role: 'student')
    end

    def logged_in?
        !current_user.nil?
    end 

    def log_out
        session.delete(:user_id)
        #@current_user = nil
    end

    

end

app/controllers/assignments_controller.rb
#this file contains working code and code that needs to be refactored.

class AssignmentsController < ApplicationController
     before_action :current_user
     #before_action :admin_only, :except => :show, :new, :create
     protect_from_forgery
 
 def index 
    if current_user
         @assignments = @current_user.assignments
    else
         @assignments = Assignment.all
    end
end 
 
 
 
 def new
     if current_user.teacher?
         @assignment = Assignment.new
         all_students 
     else 
         redirect_to login_path, notice: "Credentials not found"
     end 
 end 
 
 def create
     @assignment = Assignment.new(assignment_params) 
  
    if @assignment.save
        #byebug
     current_user.assignments << @assignment
     #student_list.first.assignments << @assignment
    
         redirect_to "/users/#{current_user.id}/assignments"
    else 
         redirect_to "/users/#{current_user.id}/assignments/new"
    end 
 end 
 
 
 
 def show 
     @assignment = Assignment.find_by(id: params[:id])
     if !current_user.assignments.include?(@assignment) || @assignment.file == nil  #if the current user's assignments does not include this assignment then
            redirect_to assignments_path, :alert => "Access denied."
     end
 end 
 
 
 def edit 
     if !logged_in?
         redirect_to login_path
     end
     @assignment = current_user.assignments.find_by(id: params[:id])
         if @assignment.title != nil || @assignment.instructions != nil 
                 render :edit
             else 
                 redirect_to new_user_assignment_path
             end 
          
 end 
 
 def update
     assignment = Assignment.find_by(id: params[:id])
     assignment.update(assignment_params)
     assignment.save
     redirect_to user_assignments_path
 end 
 
 def destroy
     @assignment.delete
     redirect_to user_assignments_path
 end
 
 private
 
 
 
 
 def assignment_params
     params.require(:assignment).permit(:title, :instructions, :due_date, :score, :user_ids)
 end

 def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def all_students
    @students = User.all_students
  end

  
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
    

    #controller for logging in users   
   
   def index
       
   end
   
   def new
       user = User.find_by(id: session[:user_id])
       if logged_in?
           redirect_to user_assignments_path(user)
       end
   end 
   
   def create
       user = User.find_by(email: params[:session][:email].downcase)
       #byebug
       if user.teacher? && user.authenticate(params[:session][:password])
           log_in user
           redirect_to assignments_path
       elsif 
        user.student? && user.authenticate(params[:session][:password])
           log_in user
           redirect_to user_user_assignments_path(user)
       else 
           flash.now[:danger] = "Invalid email/password. Please try again."
           render :new
       end 
   end 
   
   
   
   def destroy
       log_out #if logged_in?
       redirect_to '/'
   end
   
   def google_login
    user_email = request.env['omniauth.auth']['info']['email']
    user_name = request.env['omniauth.auth']['info']['name']
    @user = User.find_or_create_by(email: user_email) do |user|
        user.username = user_name 
        user.password = SecureRandom.hex
    end 
        log_in @user
        if @user.student?
            redirect_to user_user_assignments_path(@user)
        end #the user's show page (list of assignments if student)
    end
   

end 

app/controllers/user_assignments_controller.rb
class UserAssignmentsController < ApplicationController
    before_action :current_user

def index 
    
    @user_assignments = current_user.assignments 
end 

def show 
  
    @user_assignment = current_user.assignments.find_by(id: params[:id])
    
    render :show
    
end 

private
def user_assignment_params
    params.require(:user_assignment).permit(:user_id, :assignment_id) 
end 

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    protect_from_forgery
    
    #controller for signing up users
    def index 
  
    end 
  
    def new 
      @user = User.new 
    end
    
    def create
      #byebug
      @user = User.new(user_params)
        if @user.student && @user.save
          session[:user_id] = @user.id 
          flash[:success] = "Welcome to Your Student Dashboard!"
          redirect_to login_path
        elsif @user.teacher && @user.save
          redirect_to assignments_path
        else
          render :new
        end 
      end 
 
  
    def show
      if current_user
        
        
      end
    end 
  
    private
  
      def user_params
          params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :role)
      end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index 
    
    end 
    
    
    end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/assignments/_form.html.erb
<%= form_for @assignment  do |f| %>

<%= f.label :title, "Name of Assignment:" %>
<%= f.text_field :title %>
<br>

<%= f.label :instructions, "Instructions:" %>
<%= f.text_area :instructions %>
<br>

<%= f.label :attachment, "Upload Assignment:" %>
<%= f.file_field :file %>
<br>

<%= f.label :due_date, "Due Date:" %>
<%= f.datetime_field :due_date %>
<br>

<%= f.label :score, "Score:" %>
<%= f.number_field :score %>
<br>

<%= f.label :user_ids, "Students:" %><br>
<%= f.collection_check_boxes(:user_ids, @students, :id, :first_name) %><br><br>

<%= f.submit "Create Assignment" %>
<% end %>

app/views/assignments/edit.html.erb
<h1> Edit Assignment:</h1><br>

<%= form_for @assignment do |f| %>
<%= f.label :title, "Name of Assignment:" %>
<%= f.text_field :title %>
<br>

<%= f.label :instructions, "Instructions:" %>
<%= f.text_area :instructions %>
<br>

<%= f.label :attachment, "Upload Assignment:" %>
<%= f.file_field :file %>
<br>

<%= f.label :due_date, "Due Date:" %>
<%= f.datetime_field :due_date %>
<br>

<%= f.label :score, "Score:" %>
<%= f.number_field :score %>
<br>


<br>
<%= f.submit "Edit Assignment" %>
<% end %>

<%= link_to "Back", :back  %>

app/views/assignments/index.html.erb
<h1>All Assignments</h1>

<% @assignments.each do |a| %><br>
   <%= link_to a.title, assignment_path(a) %><br>
    

<% end %><br><br>

<div>
<%= link_to "Create a New Assignment", new_assignment_path %><br>
</div>

app/views/assignments/new.html.erb
<h1> Create New Assignment:</h1><br>


<%= render "form" %>


<%= link_to "Back", "history.back()" %>

app/views/assignments/show.html.erb
<h2> Welcome, <%= @current_user.username %> !</h2><br>
<h3> This is your Assignment Dashboard </h3><br><br>
<hr><br><br>


<h1><%= @assignment.title %></h1><br><br>

<%= link_to "Open Assignment", url_for(@assignment.file) %><br><br>
<! -->

<%= @assignment.instructions %><br><br>
<h4> Due Date: </h4>
<%= @assignment.due_date.in_time_zone('US/Eastern').strftime("%d/%m/%Y %I:%M %p") %>


<br>
<br>


<%= link_to "Edit Assignment", edit_assignment_path %><br>
<%= link_to "Delete Assignment", assignment_path(@assignment), :data => {:confirm => 'Are you sure?'}, :method => :delete %><br>
<br>

<%= link_to "Back", "history.back()" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Tutor Assistant</title>
    <link href="https://fonts.googleapis.com/css2?family=Belleza&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100&display=swap" rel="stylesheet">
	  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&family=Oswald:wght@500&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    

</head>

  <body>
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>

  <nav class="navbar">
	<div class="container">
	<div class="navbar-header">
		<a href="/" class="navbar-brand">Tutor Assistant</a></div>

	<ul class="navbar-nav">
		<li class="nav-link"><a href="#">About</a></li>
		<li class="nav-link"><a href="/assignments">All Assignments</a></li>
      
	</ul>
	<ul class="navbar-right">
		<li class="nav-link"><a href="/signup">Sign Up</a></li>
		<li class="nav-link"><a href="/login">Login</li></a>
    <li class="nav-link"><%= link_to "Log Out", logout_path %></li></a>
	</ul></div>
</nav>
</div>


<div class="content-container">
  <%= yield %>
</div>

</body>








    
</html>

app/views/user_assignments/index.html.erb
<h1>Your Assignments</h1>

<% @user_assignments.each do |a| %><br><br>
    <%= link_to a.title, user_assignment_path(a) %>

<% end %>
<br>
<br>

app/views/user_assignments/show.html.erb
<h2> Welcome, <%= current_user.username %> !</h2><br>
<h3> This is your Student Dashboard </h3><br>

<div>
<h1><%= @user_assignment.title %></h1><br><br>
<%= link_to "Open Assignment", url_for(@user_assignment.file) %><br><br>

<h4> Due Date: </h4>
<%= @user_assignment.due_date.in_time_zone('US/Eastern') %>
<%= @user_assignment.due_date.in_time_zone('US/Eastern').strftime("%I:%M %p") %>
</div>

<br>
<br>

<%= form_for @user_assignment  do |f| %>

    <%= f.label :attachment, "Submit Completed Assignment:" %><br>
    <%= f.file_field :file %>
    <br><br>
<%= f.submit "Submit Assignment" %>

<% end %>
<br>
<%= link_to "Back", :back  %>

app/views/users/new.html.erb
<div class="wrapper">

<h1> Sign Up:</h1><br>

<%= form_for @user do |f| %>
<%= f.label :first_name, "First Name:" %>
<%= f.text_field :first_name %>
<br>

<%= f.label :last_name, "Last Name:" %>
<%= f.text_field :last_name %>
<br>

<%= f.label :username, "Username:" %>
<%= f.text_field :username %>
<br>

<%= f.label :email, "Email:" %>
<%= f.text_field :email %>
<br>
<%= f.label :role, "Select Role:" %>
<%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %><br>

<%= f.label :password, "Password:" %>
<%= f.password_field :password %>
<br>

<%=f.label :password_confirmation, "Confirmation" %>
<%=f.password_field :password_confirmation%>

<br>
<%= f.submit "Create my account" %>
<% end %>
</div>

app/views/users/show.html.erb
<h2> This is the show page </h2>
<h3> Welcome, <%= @current_user.username %><br/><br><br>


<%= link_to "Your Assignments", user_assignments_path(:user_id) %><br>
<%= link_to "Logout", logout_path, method: :post %>

app/views/welcome/index.html.erb
<img src="/assets/tutor-logo.png" style="width:550px;height:500px;" class="center"></img>



<br>
<button><%= link_to "Sign up", new_user_path_url %></button>
<button><%= link_to "Log In", login_path_url %></button>
<br><br>
<%= button_to "Sign-In with Google", '/auth/google_oauth2' %>